- name: modify repository
  apt_repository:
    repo: "ppa:openjdk-r/ppa"
    state: present

- name: install java
  apt:
    name: "{{ item }}"
    state: latest
    force: yes
  with_items:
    - openjdk-8-jdk
    - openjdk-8-jre
    - openjdk-8-jre-headless
